apiVersion: v1
kind: Service
metadata:
  name: fastapi-nodeport-service
spec:
  selector:
    pod-name: fast-api-pod2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort

